version: "3.9"
services:
  servidor_rethinkdb:
    image: rethinkdb
    container_name: servidor_rethinkdb
    ports:
      - "8080:8080"
      - "28015:28015"
      - "29015:29015"
    volumes:
      - /var/opt/rethinkdb:/home/app_user
  servidor_cliente:
    build: .
    image: servidor_cliente
    container_name: servidor_cliente
    depends_on:
      - servidor_rethinkdb
    stdin_open: true # docker run -i
    tty: true        # docker run -t
